baseURL = 'https://srnt.xyz/'
languageCode = 'en-us'
title = 'srnt.xyz'
    
theme = 'smol'

# Parameters
[params]
    # add the subtitle when there is some idea
    #subtitle = "i need some good subtitle here"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "posts/"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "categories/"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "tags/"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "about/"
        url = "/about/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "gpg.asc"
        url = "/gpg.asc"
        weight = 1 

    [[menu.footer]]
        name = "mail"
        url = "mailto:srnt@mailbox.org"
        weight = 2 
